version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbviajante:3306/dbviajante
      SPRING_DATASOURCE_USERNAME: pv
      SPRING_DATASOURCE_PASSWORD: pv
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      dbviajante:
        condition: service_healthy
    networks:
      - backend

  dbviajante:
    image: mysql:8.0
    container_name: dbviajante
    restart: always
    environment:
      - MYSQL_DATABASE=dbviajante
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=pv
      - MYSQL_PASSWORD=pv
    ports:
      - '4306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - backend

volumes:
  mysql_data:
networks:
  backend:
    driver: bridge
